version: "3.9"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    command: sh -c "pnpm install && pnpm dev"
    environment:
      - CI=true
    volumes:
      - ./:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - "3000:3000"
    env_file:
      - .env.docker.local
    depends_on:
      - db
      - mailhog

  db:
    image: postgres:15-alpine
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: app_db
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  pgadmin:
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@local.dev
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    depends_on:
      - db

  mailhog:
    image: mailhog/mailhog:latest
    restart: always
    ports:
      - "1025:1025"   # SMTP port
      - "8025:8025"   # Web UI port

volumes:
  pgdata:
